// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9jXKoJ4IrO7PjKGksBNtbw_lQ_230W5k',
    appId: '1:169007340701:android:71e71186907eb9ccc88874',
    messagingSenderId: '169007340701',
    projectId: 'eventpro-dev',
    storageBucket: 'eventpro-dev.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCgwxvBVRH-8vahe53ga6682xTviTfFN4s',
    appId: '1:169007340701:ios:5ace93eb5bc58a9fc88874',
    messagingSenderId: '169007340701',
    projectId: 'eventpro-dev',
    storageBucket: 'eventpro-dev.firebasestorage.app',
    iosBundleId: 'com.eventpro.spike.firebaseSpike',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCgwxvBVRH-8vahe53ga6682xTviTfFN4s',
    appId: '1:169007340701:ios:5ace93eb5bc58a9fc88874',
    messagingSenderId: '169007340701',
    projectId: 'eventpro-dev',
    storageBucket: 'eventpro-dev.firebasestorage.app',
    iosBundleId: 'com.eventpro.spike.firebaseSpike',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAUixQnJMMgdoRQu1x--pwgKVSJ810QpTE',
    appId: '1:169007340701:web:7e1c2b7e63c70665c88874',
    messagingSenderId: '169007340701',
    projectId: 'eventpro-dev',
    authDomain: 'eventpro-dev.firebaseapp.com',
    storageBucket: 'eventpro-dev.firebasestorage.app',
  );
}
